grid_map_visualization:
  ros__parameters:
    grid_map_topic: /grid_map
    grid_map_visualizations: [occupancy_grid]
    occupancy_grid:
        type: occupancy_grid
        params:
          layer: type
          data_min: 0.0
          data_max: 1.0
