name: Colcon Build Test
on:
  push:
    branches:
    - 'rolling'
    - 'iron'
    - 'humble'
  pull_request:
    branches:
    - '*'
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'rolling', container: 'rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-desktop-latest'}
    container: 
      image: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: src/grid_map
    - name: Pull in repos with vcs
      run: |
        apt-get update
        vcs import --shallow --skip-existing --input grid_map/tools/ros2_dependencies.repos
      shell: bash
      working-directory: src
      if: ${{ matrix.config.rosdistro == 'rolling' }}
    - name: Install Dependencies with Rosdep
      run: |
        apt update
        rosdep update
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        rosdep install --from-paths src --ignore-src -y --skip-keys "slam_toolbox"
      shell: bash
    - name: Colcon Build (Release)
      run: |
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to grid_map
      shell: bash
    - name: Test
      run: |
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        source install/setup.bash
        colcon test --paths src/grid_map/* --event-handlers=console_cohesion+
        colcon test-result --all --verbose
      shell: bash

