name: Colcon Build Test
on:
  push:
    branches:
    - 'rolling'
    - 'iron'
    - 'humble'
  pull_request:
    branches:
    - '*'
jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'humble', container: 'ros:humble'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: src/grid_map
    - name: Install Dependencies with Rosdep
      run: |
        apt update
        rosdep update
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        rosdep install --from-paths src --ignore-src -y --skip-keys "slam_toolbox turtlebot3_gazebo gazebo_ros_pkgs"
      shell: bash
    - name: Colcon Build (Release)
      run: |
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to grid_map
      shell: bash
    - name: Test
      run: |
        source /opt/ros/${{matrix.config.rosdistro}}/setup.bash
        source install/setup.bash
        colcon test --return-code-on-test-failure --paths src/grid_map/* --event-handlers=console_cohesion+
        colcon test-result --all --verbose
      shell: bash

